export const overdueActionTypes = {
    GET_OVERDUE_START: 'GET_OVERDUE_START',
    GET_OVERDUE_SUCCESS: 'GET_OVERDUE_SUCCESS',
    GET_OVERDUE_FAILURE: 'GET_OVERDUE_FAILURE',
    SET_PREV_DOC: 'SET_PREV_DOC',
    GET_MORE_OVERDUE_START: 'GET_MORE_OVERDUE_START',
    GET_MORE_OVERDUE_SUCCESS: 'GET_MORE_OVERDUE_SUCCESS',
    GET_MORE_OVERDUE_FAILURE: 'GET_MORE_OVERDUE_FAILURE'
}