export const dueTodayActionTypes = {
    GET_DUE_TODAY_START: 'GET_DUE_TODAY_START',
    GET_DUE_TODAY_SUCCESS: 'GET_DUE_TODAY_SUCCESS',
    GET_DUE_TODAY_FAILURE: 'GET_DUE_TODAY_FAILURE',
    SET_PREV_DOC: 'SET_PREV_DOC',
    GET_MORE_DUE_TODAY_START: 'GET_MORE_DUE_TODAY_START',
    GET_MORE_DUE_TODAY_SUCCESS: 'GET_MORE_DUE_TODAY_SUCCESS',
    GET_MORE_DUE_TODAY_FAILURE: 'GET_MORE_DUE_TODAY_FAILURE'
}