export const ticketActionTypes = {
    GET_TICKET_START: 'GET_TICKET_START',
    GET_TICKET_SUCCESS: 'GET_TICKET_SUCCESS',
    GET_TICKET_FAILURE: 'GET_TICKET_FAILURE',
    COMPLETE_TASK_START: 'COMPLETE_TASK_START',
    COMPLETE_TASK_SUCCESS: 'COMPLETE_TASK_SUCCESS',
    COMPLETE_TASK_FAILURE: 'COMPLETE_TASK_FAILURE'
}