export const completedActionTypes = {
    GET_COMPLETED_START: 'GET_COMPLETED_START',
    GET_COMPLETED_SUCCESS: 'GET_COMPLETED_SUCCESS',
    GET_COMPLETED_FAILURE: 'GET_COMPLETED_FAILURE',
    SET_COMPLETED_PREV_DOC: 'SET_COMPLETED_PREV_DOC',
    GET_MORE_COMPLETED_START: 'GET_MORE_COMPLETED_START',
    GET_MORE_COMPLETED_SUCCESS: 'GET_MORE_COMPLETED_SUCCESS',
    GET_MORE_COMPLETED_FAILURE: 'GET_MORE_COMPLETED_FAILURE',
}