export const  userActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    GET_USER_DETAIL_START: 'GET_USER_DETAIL_START',
    GET_USER_DETAIL_SUCCESS: 'GET_USER_DETAIL_SUCCESS',
    GET_USER_DETAIL_FAILURE: 'GET_USER_DETAIL_FAILURE',
}